/* oxlint-disable no-unsafe-assignment, no-unsafe-member-access, no-unsafe-argument */
/**
 * TASK 1.5R — PHASE 4 — Fault Corpus R-001..R-018 as an in-repo regression.
 *
 * The corpus lives in `artifacts/handoff/TASK-1.5R/faults/` (fixture +
 * verdict per fault, generated by `generate.py`) and is also run standalone
 * by `artifacts/handoff/TASK-1.5R/run-fault-corpus.mjs`. This spec drives the
 * same `run-fault.ts` driver against the same fixtures so the corpus is part
 * of the vitest regression run, not just a handoff artifact.
 *
 * Each fixture pins:
 *   - the store-level root cause via `expected_ingest_reason_matches`
 *     (structural attacks R-001..R-013 are refused at `put()` time), and
 *   - the bridge-level verdict + reason keywords (semantic attacks
 *     R-014..R-017 are accepted by the store and blocked by the bridge;
 *     R-012 / R-013 / R-018 PASS).
 */
import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { evaluateIrBridge } from '../../src/ir/bridge.ts'
import { ModelingIr, type IrIngestVerdict, type IrKind } from '../../src/ir/index.ts'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const faultDir = join(__dirname, '..', '..', '..', '..', '..', 'artifacts', 'handoff', 'TASK-1.5R', 'faults')

const fixtureNames = readdirSync(faultDir)
  .filter(name => name.endsWith('.json') && !name.endsWith('.verdict.json'))
  .sort()

describe('TASK 1.5R fault corpus R-001..R-018', () => {
  for (const name of fixtureNames) {
    const id = name.replace(/\.json$/, '')
    const fixture = JSON.parse(readFileSync(join(faultDir, name), 'utf8'))
    const verdict = JSON.parse(readFileSync(join(faultDir, name.replace(/\.json$/, '.verdict.json')), 'utf8'))

    it(`${id} — ${fixture.description}`, () => {
      const ir = new ModelingIr({ now: () => '2026-08-30T00:00:00.000Z' })
      const refused: { kind: string; failures: ReadonlyArray<{ path: string; kind: string; reason: string }> }[] = []
      for (const entry of fixture.ingest) {
        const result = ir.put(entry.kind as IrKind, entry.value) as IrIngestVerdict
        if (!result.accepted) refused.push({ kind: entry.kind, failures: result.failures })
      }

      const decision = evaluateIrBridge(ir, fixture.ir_claims ?? [], fixture.mode)

      expect(decision.status).toBe(verdict.expected_status)

      for (const needle of verdict.expected_reason_matches ?? []) {
        expect(decision.reason).toContain(needle)
      }

      // Store-level root cause: the refused ingest must carry the attacked
      // field with the expected failure class.
      const haystack = refused
        .flatMap(e => e.failures.map(f => `${f.path}:${f.kind}:${f.reason}`))
        .join(' | ')
      for (const needle of verdict.expected_ingest_reason_matches ?? []) {
        expect(haystack).toContain(needle)
      }
    })
  }
})
